name: 'site'
version: 0.1.0
description: >
  The site for directcode.org.
homepage: https://www.directcode.org
environment:
  sdk: '>=1.8.0'
dependencies:
  browser: any
  polymer: ">=0.15.2 <0.16.0"
  paper_elements: ">=0.6.0 <0.7.0"
  core_elements: ">=0.5.0 <0.6.0"
transformers:
- polymer:
    entry_points: web/index.html
